### PR TITLE
Cmake updates

### PR DESCRIPTION
**Pull request by bandre-ucar**
Updates the cmake configuration to address issues related to compilers, blas, and hpc machines. Removes unused configuration logic related to silo.  Update doc for running on yellowstone.

Please test on nersc machines before accepting pull request.

### CODE REVIEW

**Comment by bandre-ucar** [comment]
Local and travis build are good. Just waiting for nersc testing.

**Comment by bishtgautam** [comment]
Out-of-the-box build on Edison fails. Is SBeTR expected to build it's own HDF5 or use system installed HDF5? When system installed HDF5 is not loaded, the build fails because `HDF5_DIR` is not found. To get the build system underway without using system installed HDF5 few changes had to be made. SBeTR is able to build it's own HDF5 but crashes while building netcdf. More information is available at 
https://gist.github.com/bishtgautam/9fc1adf52dcd7c6323625cc1f84b343e

**Comment by bandre-ucar** [comment]
My understanding of Jeff's platform dependent code is that the cray compilers are broken wrt hdf5 for some reason. Our choice is to use cray with his platform dependent code, or use not cray and build it ourselves.

If we don't want any system installed modules for hdf5 or netcdf, we have to switch to intel, and your change to the planform config is one correct. It's what I suggested in #11 but can't test.

If we want to support cray, then we need someone to debug it.

For standalone betr, I don't see much benefit to the cray route. I think that is what Jinyun did with cori. When betr is integrated into cesm/acme, then it will be configured with their pre-debugged versions.

**Comment by jinyun1tang** [comment]
Gautam
  Did you get it worked out on edison?

**Comment by bandre-ucar** [comment]
I don't think edison will work until #11 is taken care of.

**Comment by bishtgautam** [comment]
The config worked using `make config FC=ifort CC=icc CXX=icpc`, but the `make install FC=ifort CC=icc CXX=icpc` because of missing  `daxpy` from BLAS. I'm trying again with `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -mkl")` set in `cmake/Modules/set_up_platform.cmake` under Edison. Building of HDF5 and netcdf takes a while.

**Comment by bishtgautam** [comment]
Btw `make config FC=ftn CC=cc CXX=CC` didn't work.

**Comment by jinyun1tang** [comment]
I think -mkl has no effect from my last try on cori. Have you removed the
hardwired cc CC compiler for edison in set_up_platform.cmake? If not, that
will override what you passed from the command line.

**Comment by bishtgautam** [comment]
Including `-mkl` fixes the `undefined reference to daxpy`.  Though,  `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -mkl")` should have been `set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mkl")`

**Comment by bishtgautam** [comment]
I didn't like the solution of putting `set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mkl")` in cmake/Modules/set_up_platform.cmake because we are assuming the compiler is always intel on Edison. Probably we can't add `-mkl` for all intel compiler because this a NERSC related weirdness going on here. Here is an alternate solution https://gist.github.com/bishtgautam/28884004c141bea454537ecf9867d3f0

**Comment by bandre-ucar** [comment]
Adding -mlk broke things on yellowstone. Jeff seemed to think it wasn't necessary. I'm ok with your proposed solution. Should we make that change as part of #11, or do you want me to update and retest this PR?

**Comment by bishtgautam** [comment]
I will merge this PR as is and open a separate PR to fix #11.

**Comment by jinyun1tang** [comment]
I am too for Gautam's solution. Ben, if you can update it, it would be nice.

**Pull request merged**
